### ISSUE TITLE
Can't install with 2.2

### ISSUE THREAD

**Issue by sedax90** [it4mage/magento2-traduzione-italiana#10]
Actually is not possibile to upgrade to M2.2 with composer because:

> Installation request for antoniocarboni/magento2-traduzione-italiana dev-master -> satisfiable by antoniocarboni/magento2-traduzione-italiana[dev-master].
>     - antoniocarboni/magento2-traduzione-italiana dev-master requires magento/framework 100.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.2.0-rc20, 100.1.9, 100.0.18].

**Comment by afavata** [comment]
Still the same issue:

composer require magento2translations/language_it_it:dev-master

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento2translations/language_it_it dev-master -> satisfiable by magento2translations/language_it_it[dev-master].
    - Conclusion: remove magento/framework 101.0.0
    - Conclusion: don't install magento/framework 101.0.0
    - magento2translations/language_it_it dev-master requires magento/framework ~100.0 -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.2.0-rc20, 100.1.9, 100.0.18].
    - Can only install one of: magento/framework[101.0.0, 100.0.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.6].
    - Can only install one of: magento/framework[101.0.0, 100.0.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.8].
    - Can only install one of: magento/framework[101.0.0, 100.0.9].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
    - Can only install one of: magento/framework[101.0.0, 100.1.0].
    - Can only install one of: magento/framework[101.0.0, 100.0.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.11].
    - Can only install one of: magento/framework[101.0.0, 100.1.1].
    - Can only install one of: magento/framework[101.0.0, 100.0.12].
    - Can only install one of: magento/framework[101.0.0, 100.1.2].
    - Can only install one of: magento/framework[101.0.0, 100.1.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.13].
    - Can only install one of: magento/framework[101.0.0, 100.1.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.14].
    - Can only install one of: magento/framework[101.0.0, 100.1.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.15].
    - Can only install one of: magento/framework[101.0.0, 100.1.6].
    - Can only install one of: magento/framework[101.0.0, 100.1.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.16].
    - Can only install one of: magento/framework[101.0.0, 100.0.17].
    - Can only install one of: magento/framework[101.0.0, 100.1.8].
    - Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
    - Can only install one of: magento/framework[101.0.0, 100.1.9].
    - Can only install one of: magento/framework[101.0.0, 100.0.18].
    - Installation request for magento/framework (locked at 101.0.0) -> satisfiable by magento/framework[101.0.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by elymania** [comment]
Same problem. 
I get this error:
`Loading composer repositories with package information                                                            Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - antoniocarboni/magento2-traduzione-italiana dev-master requires magento/framework 100.* -> no matching package found.
    - antoniocarboni/magento2-traduzione-italiana dev-master requires magento/framework 100.* -> no matching package found.
    - Installation request for antoniocarboni/magento2-traduzione-italiana dev-master -> satisfiable by antoniocarboni/magento2-traduzione-italiana[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

I have edited the composer.json inside root magento in this way:
`.....
    "require": {

        "magento/framework": "*",     <<<< ADD LINE

        "magento/product-community-edition": "2.2.0",

        "composer/composer": "@alpha",

        "magento/module-bundle-sample-data": "100.2.*",

        "magento/module-catalog-sample-data": "100.2.*",

        "magento/module-customer-sample-data": "100.2.*",

        "magento/module-theme-sample-data": "100.2.*",

        "magento/module-widget-sample-data": "100.2.*",

        "magento/module-cms-sample-data": "100.2.*",

        "magento/module-review-sample-data": "100.2.*",

        "magento/module-tax-sample-data": "100.2.*",

        "magento/module-msrp-sample-data": "100.2.*",

        "magento/module-sales-sample-data": "100.2.*",

        "magento/module-catalog-rule-sample-data": "100.2.*",

        "magento/module-configurable-sample-data": "100.2.*",

        "magento/module-product-links-sample-data": "100.2.*",

        "magento/module-wishlist-sample-data": "100.2.*",

        "magento/module-sales-rule-sample-data": "100.2.*",

        "magento/module-downloadable-sample-data": "100.2.*",

        "magento/module-grouped-product-sample-data": "100.2.*",

        "magento/module-swatches-sample-data": "100.2.*",

        "magento/sample-data-media": "100.2.*",

        "magento/module-offline-shipping-sample-data": "100.2.*",

        "antoniocarboni/magento2-traduzione-italiana":"dev-master"   <<<< ADD LINE

    },
.....................
    "repositories": [
        {

                "type": "vcs",       <<<<<<<< ADD LINE
                "url":  "https://github.com/antoniocarboni/magento2-traduzione-italiana"   <<<<< EDIT LINE

        }
    ],
..........`

I tryed to add 
`"magento/framework": "*"`
inside requirement block but with the same result.

**Comment by yupswing** [comment]
@antoniocarboni it's impossible to install the italian translation with Magento 2.2 (framework 101.*).
Is it possible to receive an update???

**Comment by DavidLambauer** [comment]
I just forked the repo and disabled the require of Magento. This is the quick fix to install and use the module until it is maintained. 

You can use it: 

```
composer config repositories.repo-name vcs https://github.com/DavidLambauer/magento2-traduzione-italiana 
composer require davidlambauer/magento2-traduzione-italiana
```

**Comment by yupswing** [comment]
In the the end I actually just installed manually (as explained in the README.MD) and everything went fine (I guess it's not much different than the composer package since there is no update to the translation if the repo is not maintained).

Thanks for the fork btw.

**Comment by rumbdev** [comment]
hi there,
just in case someone is still in trouble: you can use [mageplaza italian language pack](https://github.com/mageplaza/magento-2-italian-language-pack) if you want to upgrade smoothly via composer (tested in 2.2.0 and 2.2.1). 
Just make a copy of your it_IT before removing it.
cheers!

**Comment by DavidLambauer** [comment]
@romeof1980 Thank you! I replaced the it_IT Language Pack in the [M2 Awesome List](https://github.com/DavidLambauer/awesome-magento2). Yours is now listed.

**Comment by LucaGallinari** [comment]
Thanks to #13 the module is now compatible with 2.2.*
