### ISSUE TITLE
Installazione Effettuata sito resta in Inglese.

### ISSUE THREAD

**Issue by niomax** [it4mage/magento2-traduzione-italiana#15]
Buongiorno a tutti,
Ho installato e configurato la traduzione di magento , il tutto senza errori apparenti ma continuo a vedere frontend e backend in inglese.
Di tradotto vedo solo alcuni elementi come i nomi dei paesi , i giorni della settimana....da cosa può dipendere ?
Stessa anomalia se provo a mettere tedesco o francese ...

Grazie in anticipo a tutti.

![screenshot_20180420_084831](https://user-images.githubusercontent.com/38543012/39034860-3796df42-4478-11e8-8912-a1f8a342ceb1.png)
![screenshot_20180420_084850](https://user-images.githubusercontent.com/38543012/39034864-3ba16d64-4478-11e8-9c31-68e5882f48e8.png)
![screenshot_20180420_084932](https://user-images.githubusercontent.com/38543012/39034865-3eacd5fc-4478-11e8-8acc-08a7bebd0edd.png)

**Comment by ignition3d** [comment]
ciao, scusa il disturbo.
hai risolto?

io non riesco ad installare. mi chiede user e password:
[Composer\Downloader\TransportException]                                     
Invalid credentials for 'https://repo.magento.com/packages.json', aborting.

sai quali credenziali devo inserire. io inserisco quelle di GitHub, ma mi da questo errore.

grazie mille per l'aiuto

**Comment by giuseppemorelli** [comment]
Ciao @niomax ,
servirebbero un po' più di dettagli, tipo:
- sei in modalità developer o production?
- nella cartella `pub/static/` di magento andando a sfogliare le cartelle trovi solo en_US oppure anche it_IT?

Per quanto riguarda @ignition3d : l'accesso a repo.magento.com è concesso previa creazione di authentication keys.
Segui questa procedura per ottenerle:

https://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

**Comment by robmagdev** [comment]
Ciao a tutti,
ho riscontrato lo stesso problema di niomax.
Sono in dev mode  e dentro pub/static sia nella cartella adminhtml che frontend sono presenti le cartelle it_IT.
Inutile dire che ho aggiornato la cache .

Qualche suggerimento?

Grazie mille in anticipo

**Comment by WaPoNe** [comment]
Risolto con la PR #17
