### ISSUE TITLE
Error installing on Ubuntu and Magento 2.2.5 CE

### ISSUE THREAD

**Issue by gitgiangalbe** [it4mage/magento2-traduzione-italiana#18]
**Linux Version:**
Linux 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Magento Version:**
Magento CE 2.2.5

Tryng to install i receive error below:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for it4mage/magento2-traduzione-italiana ^3.0 -> satisfiable by it4mage/magento2-traduzione-italiana[3.0.0].
    - it4mage/magento2-traduzione-italiana 3.0.0 requires magento/framework 100.0.*|100.1.*|101.0.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

Someone help me?

**Comment by LucaGallinari** [comment]
Hi, what do you get if you launch the following command?

> composer info magento/framework

**Comment by gitgiangalbe** [comment]
I receive:

name     : magento/framework
descrip. : N/A
keywords :
versions : * 101.0.5
type     : magento2-library
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/l        icenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/        licenses/AFL-3.0.html#licenseText
source   : []
dist     : [zip] https://repo.magento.com/archives/magento/framework/magento-fra        mework-101.0.5.0.zip
names    : magento/framework

autoload
psr-4
Magento\Framework\ => .
files

requires
colinmollenhour/php-redis-session-abstract 1.3.4
composer/composer ^1.4
ext-bcmath *
ext-curl *
ext-dom *
ext-gd *
ext-hash *
ext-iconv *
ext-mcrypt *
ext-openssl *
ext-simplexml *
ext-spl *
ext-xsl *
lib-libxml *
magento/zendframework1 ~1.13.0
monolog/monolog ^1.17
oyejorge/less.php ~1.7.0
php ~7.0.13|~7.1.0
symfony/console ~2.3, !=2.7.0
symfony/process ~2.1
tedivm/jshrink ~1.3.0
zendframework/zend-code ~3.1.0
zendframework/zend-crypt ^2.6.0
zendframework/zend-http ^2.6.0
zendframework/zend-mvc ~2.7.12
zendframework/zend-stdlib ^2.7.7
zendframework/zend-uri ^2.5.1
zendframework/zend-validator ^2.6.0

suggests
ext-imagick Use Image Magick >=3.0.0 as an optional alternative image processing         library
