### ISSUE TITLE
Aggiornamento per compatibilità con magento 2.1

### ISSUE THREAD

**Issue by GardeTV** [it4mage/magento2-traduzione-italiana#2]
Ciao,

tentando di aggiornare l'installazione magento alle versione 2.1 via composer, viene restituito un errore riferito alla versione del framework magento, presente nel composer.json del modulo:

```
"require": {
    "magento/framework": "100.0.*"
},
```

Credo basti cambiare la dipendenza in:

```
    "magento/framework": "100.2.*"
```

**Comment by bordeo** [comment]
Risolto con la [pull request 3](https://github.com/antoniocarboni/magento2-traduzione-italiana/pull/3)
