### ISSUE TITLE
modifica file composer.json

### ISSUE THREAD

**Issue by macgus62** [it4mage/magento2-traduzione-italiana#4]
gli apici (complice la tastiera italiana) non sono corretti. 
La modifica corretta è la seguente:
"require": {
    ...
 "antoniocarboni/magento2-traduzione-italiana": "dev-master"
    },
     "repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/antoniocarboni/magento2-traduzione-italiana"
        }
    ],

NOTA: ricordate di mettere la virgola alla fine della stringa che precede "antoniocarboni/magento2-traduzione-italiana": "dev-master"

**Comment by Seraph63** [comment]
Ciao,
Ho installato Magento 2.1.3 in locale, in Admin->System Config->inserisco 'Public Access key' e 'Private ACess Key'->click on 'Save Config' appare questo messaggio:

Command "show" failed: Reading composer.json of antoniocarboni/magento2-traduzione-italiana (master)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.0.4)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.0.7)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.1.0)[Composer\Repository\InvalidRepositoryException] No valid composer.json was found in any branch or tag of https://github.com/antoniocarboni/magento2-traduzione-italiana, could not load a package from it. show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [package] [version] 

Qualche idea?
Grazie

**Comment by LucaGallinari** [comment]
Il file readme è stato rivisto completamente e adesso si specifica di fare semplicemente un "composer require" perché il repo è ora su packagist.
