### ISSUE TITLE
Command "show" failed: Reading composer.json

### ISSUE THREAD

**Issue by Seraph63** [it4mage/magento2-traduzione-italiana#5]
Ciao,
Ho installato Magento 2.1.3 in locale, in Admin->System Config->inserisco 'Public Access key' e 'Private ACess Key'->click on 'Save Config' appare questo messaggio:

Command "show" failed: Reading composer.json of antoniocarboni/magento2-traduzione-italiana (master)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.0.4)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.0.7)Reading composer.json of antoniocarboni/magento2-traduzione-italiana (2.1.0)[Composer\Repository\InvalidRepositoryException] No valid composer.json was found in any branch or tag of https://github.com/antoniocarboni/magento2-traduzione-italiana, could not load a package from it. show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [package] [version] 

Qualche idea?
Grazie

**Comment by giuseppemorelli** [comment]
Il repository è stato spostato da antoniocarboni/magento2-traduzione-italiana a it4mage/magento2-traduzione-italiana.
In ogni caso: la soluzione migliore è installare il tutto da shell con composer.
