### ISSUE TITLE
Missing entry

### ISSUE THREAD

**Issue by davidmonichi** [it4mage/magento2-traduzione-italiana#8]
Hi,

I found out that following entry is missing in the translation file:

`Are you sure you would like to remove this item from the shopping cart?`

here a first guess of a translation, adapt it as you think fits best:

Sei sicuro di voler eliminare il prodotto dal carrello?

Best

/david

**Comment by LucaGallinari** [comment]
I guess that the translation was present but due to a bug on old Magento2 versions (like [this issue](https://github.com/magento/magento2/issues/7525)) the translation was not correctly loaded from Magento. Now it works properly.
